[tasks.run]
description = "Start Rust Server"
script = ['''
#!/usr/bin/env bash
cargo run src/main.rs
''']

[tasks.get]
description = "Start Rust Server"
script = ['''
#!/usr/bin/env bash
curl localhost:5000
''']

[tasks.post]
description = "Start Rust Server"
script = ['''
#!/usr/bin/env bash
curl -X POST -H "Content-Type: application/json" -d '{"Name":"NoCtrlZ", "Age":"23"}' localhost:5000
''']
